CREATE TABLE departments
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    department_name        VARCHAR(255)                            NOT NULL,
    department_description VARCHAR(255),
    CONSTRAINT pk_departments PRIMARY KEY (id)
);

ALTER TABLE departments
    ADD CONSTRAINT uc_departments_departmentname UNIQUE (department_name);