CREATE TABLE patients
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patient_id         VARCHAR(255)                            NOT NULL,
    first_name         VARCHAR(255)                            NOT NULL,
    last_name          VARCHAR(255)                            NOT NULL,
    middle_name        VARCHAR(255),
    gender             VARCHAR(255),
    phone              VARCHAR(255),
    email              VARCHAR(255),
    address            VARCHAR(255),
    assigned_doctor_id BIGINT,
    assigned_nurse_id  BIGINT,
    status             VARCHAR(255),
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_patients PRIMARY KEY (id)
);

ALTER TABLE patients
    ADD CONSTRAINT uc_patients_patient UNIQUE (patient_id);

ALTER TABLE patients
    ADD CONSTRAINT FK_PATIENTS_ON_ASSIGNED_DOCTOR FOREIGN KEY (assigned_doctor_id) REFERENCES users (user_id);

ALTER TABLE patients
    ADD CONSTRAINT FK_PATIENTS_ON_ASSIGNED_NURSE FOREIGN KEY (assigned_nurse_id) REFERENCES users (user_id);