package by.bsuir.medical_application.model;

public enum NotificationType {
    PATIENT_TREATMENT_UPDATED,
    PATIENT_DEPARTMENT_ASSIGNED,
    PATIENT_DOCTOR_ASSIGNED,
    PATIENT_NURSE_ASSIGNED,
    ACCOUNT_SECURITY,
    DOCTOR_PATIENT_WITHOUT_DOCTOR,
    DOCTOR_PATIENT_INDICATOR_ALERT,
    NURSE_PATIENT_TREATMENT_UPDATED,
    NURSE_PATIENT_WITHOUT_DEPARTMENT
}


